<a href="https://colab.research.google.com/github/darsh-tech/Pytorch/blob/master/Pytorch_experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import libraries

In [1]:
import torch
import numpy as np


In [2]:
x=[[1,3],[2,5]]
ok=torch.tensor(x)
print(ok)

tensor([[1, 3],
        [2, 5]])


# initializing from numpy array

In [4]:
torch.tensor(np.array(x))

tensor([[1, 3],
        [2, 5]])

In [6]:
ol=torch.ones_like(ok)
print(ol)

tensor([[1, 1],
        [1, 1]])


In [7]:
pl=torch.rand_like(ok,dtype=torch.float)
print(pl)

tensor([[0.5579, 0.5640],
        [0.8220, 0.8671]])


To select random values or constant

In [11]:
tensor=torch.rand(2,3)

To check that tensor attributes

In [19]:
print(tensor.shape)
print(tensor.dtype)
tensor.device

torch.Size([2, 3])
torch.float32


device(type='cpu')

# To load the tensor operaions to cuda rather than

In [20]:
if  torch.cuda.is_available():
    tensor=tensor.to("cuda")
    print(tensor.device)
else:
    print("cuda not available")

cuda:0


To join two or more tensors

In [23]:
pll=torch.cat([tensor,tensor,tensor],dim=1)
print(pll)

tensor([[0.5127, 0.7368, 0.5489, 0.5127, 0.7368, 0.5489, 0.5127, 0.7368, 0.5489],
        [0.1640, 0.7815, 0.4787, 0.1640, 0.7815, 0.4787, 0.1640, 0.7815, 0.4787]],
       device='cuda:0')


convert tensors to numpy

In [24]:
t=torch.ones(5)
print(t.numpy())

[1. 1. 1. 1. 1.]


convert numpy to tensors

In [25]:
nump=np.ones(5)
print(torch.from_numpy(nump))

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
